name: Build and Deploy
on:
  pull_request:
    types: [closed]
    branches:
    - master
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CI: ""
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          ref: master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
            FIREBASE_TOKEN: ${{ secrets.firebase }}
